name: Rust Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Rust
      uses: actions/setup-rust@v1.0.5
      with:
        profile: minimal

    - name: Build application
      run: |
        cargo build --release
    # Add additional steps as needed, such as running tests, etc.
